Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Webhooks
  namespace :webhooks do
    get  "whatsapp", to: proc { [ 200, {}, [ "OK" ] ] }
    post "whatsapp", to: "whatsapp#incoming"

    # Voice call webhooks
    post "voice",                     to: "voice#incoming"
    post "voice/gather",              to: "voice#gather"
    post "voice/status",              to: "voice#status"
    post "voice/confirmation",        to: "voice#confirmation"
    post "voice/confirmation_gather", to: "voice#confirmation_gather"
  end

  # Dashboard
  root "pages#dashboard"
  get "dashboard", to: "pages#dashboard"

  # Dashboard pages
  resources :appointments, only: [ :index, :show, :create, :update ] do
    collection do
      # Dedicated full-screen calendar page — just the week grid with the
      # dentist name at the top, no dashboard chrome / stat cards.
      get :calendar
    end
    member do
      patch :cancel
      patch :confirm
      patch :set_status
    end
  end
  # Diary reminders / notes (non-appointment calendar items)
  resources :calendar_notes, only: [ :create, :update, :destroy ]

  resources :patients, only: [ :index, :show, :create, :update, :destroy ]
  resources :conversations, only: [ :index, :show ] do
    collection do
      post :import
      get :export_tagged
    end
    member do
      post :reply
      patch :update_tags
      patch :resume_ai
    end
  end
  get "search", to: "search#index"

  # Pre-appointment reminders dashboard (Phase 9.6 sub-area #7)
  get  "reminders", to: "reminders#index"
  post "reminders/:appointment_id/send",
       to: "reminders#send_reminder",
       as: :send_reminder

  resources :notifications, only: [ :index ] do
    member do
      patch :mark_read
    end
    collection do
      post :mark_all_read
    end
  end
  get "analytics", to: "analytics#index"
  get "audit-log", to: "audit_logs#index", as: :audit_log
  get "audit-log/export", to: "audit_logs#export", as: :audit_log_export

  # ── Practice-management system (Phase 1+) — ADDITIVE, read-first ──
  get "procedure-codes", to: "procedure_codes#index", as: :procedure_codes
  get "treatment-macros", to: "treatment_macros#index", as: :treatment_macros
  resources :billing_accounts, only: [ :index, :show ], path: "accounts"
  resources :courses_of_treatment, only: [ :index, :show ], path: "courses-of-treatment"
  resources :estimates, only: [ :index ]
  resources :invoices, only: [ :index, :show ]
  get "patients/:patient_id/file", to: "patient_files#show", as: :patient_file
  get "imaging", to: "imaging#index", as: :imaging
  resources :scribe_sessions, only: [ :index, :show ], path: "scribe-sessions"
  get "recalls", to: "recalls#index", as: :recalls
  get "reporting", to: "reporting#index", as: :reporting
  get   "settings",          to: "settings#index"
  post  "settings/language", to: "settings#update_language"
  patch "settings/practice", to: "settings#update_practice", as: :settings_practice
  patch "settings/pricing",  to: "settings#update_pricing",  as: :settings_pricing

  # Public MP3 endpoint Twilio fetches via TwiML <Play>. Serves cached audio
  # generated by ElevenLabsService; missing or invalid hashes return 404.
  get "/voice/audio/:hash.mp3", to: "voice_audio#show", as: :voice_audio, format: false

  # Error pages — matched by exceptions_app when Rails catches a routing/HTTP error
  match "/404", to: "errors#not_found",    via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#server_error",  via: :all
end
